/* Creating CO_WINDOWSAPPLICATIONGROUPS configuration key */

IF NOT EXISTS(SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] ='CO_WINDOWSAPPLICATIONGROUPS')
Insert into CONFIGURATION_KEY ([KEY],DESCRIPTION,KEY_TYPE)
VALUES('CO_WINDOWSAPPLICATIONGROUPS','Application groups for windows','String')
GO

/*
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'CO_WINDOWSAPPLICATIONGROUPS') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'LDC'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWSAPPLICATIONGROUPS'),(select id from datacenter where code = 'LDC'),'COTESTDEV\application-admins;COTESTDEV\developers;COTESTDEV\Domain Admins')
GO
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'CO_WINDOWSAPPLICATIONGROUPS') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'GSL'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWSAPPLICATIONGROUPS'),(select id from datacenter where code = 'GSL'),'COTESTDEV\application-admins;COTESTDEV\developers;COTESTDEV\Domain Admins')
GO
*/
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'CO_WINDOWSAPPLICATIONGROUPS') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'CMH'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWSAPPLICATIONGROUPS'),(select id from datacenter where code = 'CMH'),'OD\od_application_admins;OD\svc_accounts_uda;OD\Domain Admins')
GO
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'CO_WINDOWSAPPLICATIONGROUPS') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'DSM'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWSAPPLICATIONGROUPS'),(select id from datacenter where code = 'DSM'),'OD\od_application_admins;OD\svc_accounts_uda;OD\Domain Admins')
GO
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'CO_WINDOWSAPPLICATIONGROUPS') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'AMS'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWSAPPLICATIONGROUPS'),(select id from datacenter where code = 'AMS'),'OD\od_application_admins;OD\svc_accounts_uda;OD\Domain Admins')
GO
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'CO_WINDOWSAPPLICATIONGROUPS') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'PCM'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWSAPPLICATIONGROUPS'),(select id from datacenter where code = 'PCM'),'COPCI\od_application_admins_PCI;COPCI\svc_accounts_uda_pci;COPCI\Domain Admins')
GO

/* Creating CO_SQLSERVERINSTALLERUSER Configuration key */

IF NOT EXISTS(SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] ='CO_SQLSERVERINSTALLERUSER')
Insert into CONFIGURATION_KEY ([KEY],DESCRIPTION,KEY_TYPE)
VALUES('CO_SQLSERVERINSTALLERUSER','Sqlserver Installation user','String')
GO

/*
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'CO_SQLSERVERINSTALLERUSER') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'LDC'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_SQLSERVERINSTALLERUSER'),(select id from datacenter where code = 'LDC'),'COTESTDEV\svc_sqladmin-dev')
GO
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'CO_SQLSERVERINSTALLERUSER') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'GSL'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_SQLSERVERINSTALLERUSER'),(select id from datacenter where code = 'GSL'),'COTESTDEV\svc_sqladmin-dev')
GO
*/
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'CO_SQLSERVERINSTALLERUSER') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'CMH'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_SQLSERVERINSTALLERUSER'),(select id from datacenter where code = 'CMH'),'OD\svc_sqladmin')
GO
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'CO_SQLSERVERINSTALLERUSER') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'DSM'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_SQLSERVERINSTALLERUSER'),(select id from datacenter where code = 'DSM'),'OD\svc_sqladmin')
GO
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'CO_SQLSERVERINSTALLERUSER') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'AMS'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_SQLSERVERINSTALLERUSER'),(select id from datacenter where code = 'AMS'),'OD\svc_sqladmin')
GO
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'CO_SQLSERVERINSTALLERUSER') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'PCM'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_SQLSERVERINSTALLERUSER'),(select id from datacenter where code = 'PCM'),'COPCI\svc_sqladmin_pci')
GO



/* Creating CO_SQLSERVERDBAGROUPS Configuration key */

IF NOT EXISTS(SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] ='CO_SQLSERVERDBAGROUPS')
Insert into CONFIGURATION_KEY ([KEY],DESCRIPTION,KEY_TYPE)
VALUES('CO_SQLSERVERDBAGROUPS','DBA groups for sqlserver','String')
GO

/*
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'CO_SQLSERVERDBAGROUPS') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'LDC'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_SQLSERVERDBAGROUPS'),(select id from datacenter where code = 'LDC'),'COTESTDEV\dev_dba')
GO
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'CO_SQLSERVERDBAGROUPS') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'GSL'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_SQLSERVERDBAGROUPS'),(select id from datacenter where code = 'GSL'),'COTESTDEV\dev_dba')
GO
*/
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'CO_SQLSERVERDBAGROUPS') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'CMH'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_SQLSERVERDBAGROUPS'),(select id from datacenter where code = 'CMH'),'OD\od_dba')
GO
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'CO_SQLSERVERDBAGROUPS') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'DSM'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_SQLSERVERDBAGROUPS'),(select id from datacenter where code = 'DSM'),'OD\od_dba')
GO
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'CO_SQLSERVERDBAGROUPS') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'AMS'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_SQLSERVERDBAGROUPS'),(select id from datacenter where code = 'AMS'),'OD\od_dba')
GO
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'CO_SQLSERVERDBAGROUPS') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'PCM'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_SQLSERVERDBAGROUPS'),(select id from datacenter where code = 'PCM'),'COPCI\od_dba_pci')
GO

/*
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES 
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWSAPPLICATIONGROUPS'),(select id from datacenter where code = 'LDC'),'COTESTDEV\application-admins;COTESTDEV\developers;COTESTDEV\Domain Admins'),
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWSAPPLICATIONGROUPS'),(select id from datacenter where code = 'GSL'),'COTESTDEV\application-admins;COTESTDEV\developers;COTESTDEV\Domain Admins'),
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWSAPPLICATIONGROUPS'),(select id from datacenter where code = 'CMH'),'OD\od_application_admins;OD\svc_accounts_uda;OD\Domain Admins'),
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWSAPPLICATIONGROUPS'),(select id from datacenter where code = 'DSM'),'OD\od_application_admins;OD\svc_accounts_uda;OD\Domain Admins'),
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWSAPPLICATIONGROUPS'),(select id from datacenter where code = 'AMS'),'OD\od_application_admins;OD\svc_accounts_uda;OD\Domain Admins'),
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWSAPPLICATIONGROUPS'),(select id from datacenter where code = 'PCM'),'COPCI\od_application_admins_PCI;COPCI\svc_accounts_uda_pci;COPCI\Domain Admins')


Insert into CONFIGURATION_KEY ([KEY],DESCRIPTION,KEY_TYPE)
VALUES('CO_SQLSERVERINSTALLERUSER','Sqlserver Installation user','String')

INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES 
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_SQLSERVERINSTALLERUSER'),(select id from datacenter where code = 'LDC'),'COTESTDEV\svc_sqladmin-dev'),
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_SQLSERVERINSTALLERUSER'),(select id from datacenter where code = 'GSL'),'COTESTDEV\svc_sqladmin-dev'),
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_SQLSERVERINSTALLERUSER'),(select id from datacenter where code = 'CMH'),'OD\svc_sqladmin'),
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_SQLSERVERINSTALLERUSER'),(select id from datacenter where code = 'DSM'),'OD\svc_sqladmin'),
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_SQLSERVERINSTALLERUSER'),(select id from datacenter where code = 'AMS'),'OD\svc_sqladmin'),
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_SQLSERVERINSTALLERUSER'),(select id from datacenter where code = 'PCM'),'COPCI\svc_sqladmin_pci')

Insert into CONFIGURATION_KEY ([KEY],DESCRIPTION,KEY_TYPE)
VALUES('CO_SQLSERVERDBAGROUPS','DBA groups for sqlserver','String')

INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES 
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_SQLSERVERDBAGROUPS'),(select id from datacenter where code = 'LDC'),'COTESTDEV\dev_dba'),
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_SQLSERVERDBAGROUPS'),(select id from datacenter where code = 'GSL'),'COTESTDEV\dev_dba'),
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_SQLSERVERDBAGROUPS'),(select id from datacenter where code = 'CMH'),'OD\od_dba'),
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_SQLSERVERDBAGROUPS'),(select id from datacenter where code = 'DSM'),'OD\od_dba'),
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_SQLSERVERDBAGROUPS'),(select id from datacenter where code = 'AMS'),'OD\od_dba'),
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_SQLSERVERDBAGROUPS'),(select id from datacenter where code = 'PCM'),'COPCI\od_dba_pci')
*/