/* Creating LB_RESOURCENAME configuration key */

IF NOT EXISTS(SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] ='LB_RESOURCENAME')
Insert into CONFIGURATION_KEY ([KEY],DESCRIPTION,KEY_TYPE)
VALUES('LB_RESOURCENAME','LB Resourcename for CO','String')
GO

/*
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'LB_RESOURCENAME') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'LDC'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'LB_RESOURCENAME'),(select id from datacenter where code = 'LDC'),'network_administrators')
GO
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'LB_RESOURCENAME') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'GSL'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'LB_RESOURCENAME'),(select id from datacenter where code = 'GSL'),'network_administrators')
GO
*/
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'LB_RESOURCENAME') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'CMH'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'LB_RESOURCENAME'),(select id from datacenter where code = 'CMH'),'automation_admins')
GO
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'LB_RESOURCENAME') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'DSM'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'LB_RESOURCENAME'),(select id from datacenter where code = 'DSM'),'automation_admins')
GO
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'LB_RESOURCENAME') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'AMS'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'LB_RESOURCENAME'),(select id from datacenter where code = 'AMS'),'automation_admins')
GO
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'LB_RESOURCENAME') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'PCM'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'LB_RESOURCENAME'),(select id from datacenter where code = 'PCM'),'automation_admins')
GO



/* Creating LB_ACCOUNTNAME configuration key */

IF NOT EXISTS(SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] ='LB_ACCOUNTNAME')
Insert into CONFIGURATION_KEY ([KEY],DESCRIPTION,KEY_TYPE)
VALUES('LB_ACCOUNTNAME','LB Accountname for CO','String')
GO

/*
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'LB_ACCOUNTNAME') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'LDC'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'LB_ACCOUNTNAME'),(select id from datacenter where code = 'LDC'),'vro-admin')
GO
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'LB_ACCOUNTNAME') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'GSL'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'LB_ACCOUNTNAME'),(select id from datacenter where code = 'GSL'),'vro-admin')
GO
*/
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'LB_ACCOUNTNAME') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'CMH'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'LB_ACCOUNTNAME'),(select id from datacenter where code = 'CMH'),'vro-admin')
GO
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'LB_ACCOUNTNAME') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'DSM'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'LB_ACCOUNTNAME'),(select id from datacenter where code = 'DSM'),'vro-admin')
GO
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'LB_ACCOUNTNAME') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'AMS'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'LB_ACCOUNTNAME'),(select id from datacenter where code = 'AMS'),'vro-admin')
GO
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'LB_ACCOUNTNAME') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'PCM'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'LB_ACCOUNTNAME'),(select id from datacenter where code = 'PCM'),'vro-admin')
GO



/*
Insert into CONFIGURATION_KEY ([KEY],DESCRIPTION,KEY_TYPE)
VALUES('LB_RESOURCENAME','LB Resourcename for CO','String')

INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES 
((select ID from CONFIGURATION_KEY where [KEY] = 'LB_RESOURCENAME'),(select id from datacenter where code = 'LDC'),'network_administrators'),
((select ID from CONFIGURATION_KEY where [KEY] = 'LB_RESOURCENAME'),(select id from datacenter where code = 'GSL'),'network_administrators'),
((select ID from CONFIGURATION_KEY where [KEY] = 'LB_RESOURCENAME'),(select id from datacenter where code = 'CMH'),'automation_admins'),
((select ID from CONFIGURATION_KEY where [KEY] = 'LB_RESOURCENAME'),(select id from datacenter where code = 'DSM'),'automation_admins'),
((select ID from CONFIGURATION_KEY where [KEY] = 'LB_RESOURCENAME'),(select id from datacenter where code = 'AMS'),'automation_admins'),
((select ID from CONFIGURATION_KEY where [KEY] = 'LB_RESOURCENAME'),(select id from datacenter where code = 'PCM'),'automation_admins')

Insert into CONFIGURATION_KEY ([KEY],DESCRIPTION,KEY_TYPE)
VALUES('LB_ACCOUNTNAME','LB Accountname CO','String')

INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES 
((select ID from CONFIGURATION_KEY where [KEY] = 'LB_ACCOUNTNAME'),(select id from datacenter where code = 'LDC'),'vro-admin'),
((select ID from CONFIGURATION_KEY where [KEY] = 'LB_ACCOUNTNAME'),(select id from datacenter where code = 'GSL'),'vro-admin'),
((select ID from CONFIGURATION_KEY where [KEY] = 'LB_ACCOUNTNAME'),(select id from datacenter where code = 'CMH'),'vro-admin'),
((select ID from CONFIGURATION_KEY where [KEY] = 'LB_ACCOUNTNAME'),(select id from datacenter where code = 'DSM'),'vro-admin'),
((select ID from CONFIGURATION_KEY where [KEY] = 'LB_ACCOUNTNAME'),(select id from datacenter where code = 'AMS'),'vro-admin'),
((select ID from CONFIGURATION_KEY where [KEY] = 'LB_ACCOUNTNAME'),(select id from datacenter where code = 'PCM'),'vro-admin')
*/