/* Creating CO_WINDOWS_RESOURCENAME configuration key */

IF NOT EXISTS(SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] ='CO_WINDOWS_RESOURCENAME')
Insert into CONFIGURATION_KEY ([KEY],DESCRIPTION,KEY_TYPE)
VALUES('CO_WINDOWS_RESOURCENAME','windows administrator Resourcename for CO','String')
GO

/*
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'CO_WINDOWS_RESOURCENAME') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'LDC'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWS_RESOURCENAME'),(select id from datacenter where code = 'LDC'),'local administrator')
GO
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'CO_WINDOWS_RESOURCENAME') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'GSL'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWS_RESOURCENAME'),(select id from datacenter where code = 'GSL'),'local administrator')
GO
*/
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'CO_WINDOWS_RESOURCENAME') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'CMH'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWS_RESOURCENAME'),(select id from datacenter where code = 'CMH'),'local administrator')
GO
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'CO_WINDOWS_RESOURCENAME') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'DSM'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWS_RESOURCENAME'),(select id from datacenter where code = 'DSM'),'local administrator')
GO
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'CO_WINDOWS_RESOURCENAME') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'AMS'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWS_RESOURCENAME'),(select id from datacenter where code = 'AMS'),'local administrator')
GO
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'CO_WINDOWS_RESOURCENAME') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'PCM'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWS_RESOURCENAME'),(select id from datacenter where code = 'PCM'),'local administrator')
GO

/* Creating CO_WINDOWS_ACCOUNTNAME configuration key */

IF NOT EXISTS(SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] ='CO_WINDOWS_ACCOUNTNAME')
Insert into CONFIGURATION_KEY ([KEY],DESCRIPTION,KEY_TYPE)
VALUES('CO_WINDOWS_ACCOUNTNAME','windows administrator Accountname for CO','String')
GO

/*
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'CO_WINDOWS_ACCOUNTNAME') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'LDC'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWS_ACCOUNTNAME'),(select id from datacenter where code = 'LDC'),'administrator')
GO
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'CO_WINDOWS_ACCOUNTNAME') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'GSL'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWS_ACCOUNTNAME'),(select id from datacenter where code = 'GSL'),'administrator')
GO
*/
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'CO_WINDOWS_ACCOUNTNAME') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'CMH'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWS_ACCOUNTNAME'),(select id from datacenter where code = 'CMH'),'administrator')
GO
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'CO_WINDOWS_ACCOUNTNAME') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'DSM'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWS_ACCOUNTNAME'),(select id from datacenter where code = 'DSM'),'administrator')
GO
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'CO_WINDOWS_ACCOUNTNAME') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'AMS'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWS_ACCOUNTNAME'),(select id from datacenter where code = 'AMS'),'administrator')
GO
IF NOT EXISTS (SELECT ID FROM CONFIGURATION_KEY_TO_DATACENTER WHERE CONFIGURATION_KEY_ID = (SELECT ID FROM CONFIGURATION_KEY WHERE [KEY] = 'CO_WINDOWS_ACCOUNTNAME') AND DATACENTER_ID = (SELECT ID FROM DATACENTER WHERE CODE = 'PCM'))
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWS_ACCOUNTNAME'),(select id from datacenter where code = 'PCM'),'administrator')
GO

/*

Insert into CONFIGURATION_KEY ([KEY],DESCRIPTION,KEY_TYPE)
VALUES('CO_WINDOWS_RESOURCENAME','windows Resourcename for CO','String')

INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES 
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWS_RESOURCENAME'),(select id from datacenter where code = 'LDC'),'local administrator'),
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWS_RESOURCENAME'),(select id from datacenter where code = 'GSL'),'local administrator'),
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWS_RESOURCENAME'),(select id from datacenter where code = 'CMH'),'local administrator'),
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWS_RESOURCENAME'),(select id from datacenter where code = 'DSM'),'local administrator'),
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWS_RESOURCENAME'),(select id from datacenter where code = 'AMS'),'local administrator'),
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWS_RESOURCENAME'),(select id from datacenter where code = 'PCM'),'local administrator')
		
Insert into CONFIGURATION_KEY ([KEY],DESCRIPTION,KEY_TYPE)
VALUES('CO_WINDOWS_ACCOUNTNAME','Windows Accountname CO','String')
		
INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES 
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWS_ACCOUNTNAME'),(select id from datacenter where code = 'LDC'),'administrator'),
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWS_ACCOUNTNAME'),(select id from datacenter where code = 'GSL'),'administrator'),
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWS_ACCOUNTNAME'),(select id from datacenter where code = 'CMH'),'administrator'),
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWS_ACCOUNTNAME'),(select id from datacenter where code = 'DSM'),'administrator'),
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWS_ACCOUNTNAME'),(select id from datacenter where code = 'AMS'),'administrator'),
((select ID from CONFIGURATION_KEY where [KEY] = 'CO_WINDOWS_ACCOUNTNAME'),(select id from datacenter where code = 'PCM'),'administrator')
*/