
insert into CONFIGURATION_KEY ([key],DESCRIPTION,DEFAULT_VALUE,KEY_TYPE,IS_SECURE,SHOW_ON_UI) values
('SOLARWINDS_ORION_HOST', 'OrionDB host', 'NULL', 'String', 0, 1)

INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES 
((select ID from CONFIGURATION_KEY where [KEY] = 'SOLARWINDS_ORION_HOST'),(select id from datacenter where code = 'LDC'),'oriondb1.cotestdev.local')



insert into CONFIGURATION_KEY ([key],DESCRIPTION,DEFAULT_VALUE,KEY_TYPE,IS_SECURE,SHOW_ON_UI) values
('SOLARWINDS_ORION_DB_NAME', 'OrionDB DB name', 'NULL', 'String', 0, 1)


INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES 
((select ID from CONFIGURATION_KEY where [KEY] = 'SOLARWINDS_ORION_DB_NAME'),(select id from datacenter where code = 'LDC'),'SolarWindsOrion')


insert into CONFIGURATION_KEY ([key],DESCRIPTION,DEFAULT_VALUE,KEY_TYPE,IS_SECURE,SHOW_ON_UI) values
('SOLARWINDS_ORION_INSTANCE_NAME', 'OrionDB Instance name', 'NULL', 'String', 0, 1)

INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES 
((select ID from CONFIGURATION_KEY where [KEY] = 'SOLARWINDS_ORION_INSTANCE_NAME'),(select id from datacenter where code = 'LDC'),'LOCAL')



insert into CONFIGURATION_KEY ([key],DESCRIPTION,DEFAULT_VALUE,KEY_TYPE,IS_SECURE,SHOW_ON_UI) values
('SOLARWINDS_ORION_PORT', 'OrionDB Port', 'NULL', 'String', 0, 1)

INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES 
((select ID from CONFIGURATION_KEY where [KEY] = 'SOLARWINDS_ORION_PORT'),(select id from datacenter where code = 'LDC'),'1433')


insert into CONFIGURATION_KEY ([key],DESCRIPTION,DEFAULT_VALUE,KEY_TYPE,IS_SECURE,SHOW_ON_UI) values
('SOLARWINDS_ORION_USERNAME', 'OrionDB User', 'NULL', 'String', 0, 1)

INSERT INTO CONFIGURATION_KEY_TO_DATACENTER (CONFIGURATION_KEY_ID,DATACENTER_ID,VALUE)
VALUES 
((select ID from CONFIGURATION_KEY where [KEY] = 'SOLARWINDS_ORION_USERNAME'),(select id from datacenter where code = 'LDC'),'SolarWindsOrionDatabaseUser')

